name: Readme Metrics

# NOTE:
# Can use `@latest` tag instead
# If I don't wish to version lock it

on:
  # Schedule updates Sundaily
  # https://crontab.guru/
  schedule: [{cron: "0 0 * * 0"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Base metrics
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.base.svg
          token: ${{ secrets.GH_TOKEN }}
          base: header, activity, community, repositories, metadata
          output_action: none

      - name: Fortune
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.fortune.svg
          token: NOT_NEEDED
          base: ""
          plugin_fortune: yes

      - name: Publish images
        if: ${{ success() || failure() }}
        run: |
          set +e
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git pull
          git add --all
          git commit -m "cicd: update images"
          git push --force
